# Generated by Django 4.1.7 on 2023-03-20 21:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('P', 'Patient'), ('TC', 'Treatment Center'), ('T', 'Tourist'), ('TCO', 'Tourism Company')], default='P', max_length=3)),
                ('Password', models.CharField(max_length=50)),
                ('RepeatPassword', models.CharField(max_length=50)),
                ('Token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('ProfilePicture', models.ImageField(upload_to='images/%y/%m/%d/%s')),
            ],
        ),
    ]
