# Generated by Django 4.1.7 on 2023-03-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_websiteusers_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteusers',
            name='Token',
        ),
    ]
