# Generated by Django 4.1.7 on 2023-03-21 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_doctor_picture_tourismplaces_tretment_center_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tourism_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tourismcompany')),
                ('tourism_places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tourismplaces')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.websiteusers')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
                ('treatment_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tretment_center')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.websiteusers')),
            ],
        ),
    ]
