# Generated by Django 4.1.7 on 2023-03-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tourismreservation_medicalreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreservation',
            name='status',
            field=models.CharField(default='Pending Aprroval', max_length=50),
        ),
        migrations.AddField(
            model_name='tourismreservation',
            name='status',
            field=models.CharField(default='Pending Aprroval', max_length=50),
        ),
    ]
