# Generated by Django 4.1.7 on 2023-03-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_medicalreservation_status_tourismreservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourismcompany',
            name='pictures',
        ),
        migrations.AddField(
            model_name='tourismcompany',
            name='pictures',
            field=models.ImageField(default=0, upload_to='images/%y/%m/%d'),
        ),
    ]
