# Generated by Django 4.1.7 on 2023-03-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_firstname_websiteusers_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteusers',
            name='age',
            field=models.IntegerField(),
        ),
    ]
