# Generated by Django 4.1.7 on 2023-03-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_tourismcompany_pictures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismcompany',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y/%m/%d'),
        ),
    ]
