# Generated by Django 4.1.7 on 2023-03-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_tretment_center_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='price',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
