# Generated by Django 4.1.7 on 2023-03-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_doctor_price_alter_doctor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tretment_center',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
