# Generated by Django 4.1.7 on 2023-03-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_tretment_center_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tretment_center',
            name='photos',
            field=models.ImageField(default='amr', upload_to='images/%y/%m/%d'),
        ),
    ]
