# Generated by Django 4.1.7 on 2023-03-26 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tretment_center_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tretment_center',
            name='photos',
        ),
    ]
