# Generated by Django 4.1.7 on 2023-03-26 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_websiteusers_age'),
        ('api', '0011_remove_tretment_center_photos'),
    ]

    operations = [
    ]
