# Generated by Django 4.1.7 on 2023-03-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_doctor_price_alter_doctor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteusers',
            name='picture',
            field=models.ImageField(default='amr', upload_to='images/%y/%m/%d'),
        ),
    ]
