# Generated by Django 4.1.7 on 2023-03-26 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_websiteusers_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteusers',
            name='picture',
        ),
    ]
