# Generated by Django 4.1.7 on 2023-03-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_tourismcompany_pictures'),
        ('api', '0015_remove_websiteusers_picture'),
    ]

    operations = [
    ]
