# Generated by Django 4.1.7 on 2023-03-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_tretment_center_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tretment_center',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='tretment_center',
            name='doctor_id',
            field=models.ManyToManyField(to='api.doctor'),
        ),
    ]
