# Generated by Django 4.1.7 on 2023-03-27 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20230327_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourismcompany',
            name='places',
        ),
        migrations.AddField(
            model_name='tourismplaces',
            name='image',
            field=models.ImageField(default='images/23/03/27/tourism.jpg', upload_to='places/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='tourismplaces',
            name='tourismCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tourismcompany'),
        ),
        migrations.AlterField(
            model_name='tourismcompany',
            name='pictures',
            field=models.ImageField(default='images/23/03/27/tourism.jpg', upload_to='images/%y/%m/%d'),
        ),
    ]
