# Generated by Django 4.1.7 on 2023-03-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_tretment_center_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='start_date',
            field=models.DateField(),
        ),
    ]
