# Generated by Django 4.1.7 on 2023-03-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_tourismplaces_tourismcompany'),
        ('api', '0019_alter_doctor_picture'),
    ]

    operations = [
    ]
