# Generated by Django 4.1.7 on 2023-03-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_websiteusers_picture'),
        ('api', '0020_merge_20230329_1046'),
    ]

    operations = [
    ]
