# Generated by Django 4.1.7 on 2023-03-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_tretment_center_doctor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='treatment_center',
        ),
        migrations.AddField(
            model_name='tretment_center',
            name='doctor_id',
            field=models.ManyToManyField(to='api.doctor'),
        ),
    ]
