# Generated by Django 4.1.7 on 2023-03-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_doctor_treatment_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreservation',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicalreservation',
            name='start_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tourismreservation',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tourismreservation',
            name='start_time',
            field=models.DateField(),
        ),
    ]
