# Generated by Django 4.1.7 on 2023-03-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_medicalreservation_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismplaces',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tourismplaces',
            name='start_time',
            field=models.DateField(),
        ),
    ]
