# Generated by Django 4.1.7 on 2023-03-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_tourismplaces_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismreservation',
            name='price',
            field=models.IntegerField(),
        ),
    ]
