# Generated by Django 4.1.7 on 2023-04-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_tourismreservation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismcompany',
            name='Password',
            field=models.CharField(default='109141David', max_length=50),
        ),
        migrations.AddField(
            model_name='tourismcompany',
            name='RepeatPassword',
            field=models.CharField(default='109141David', max_length=50),
        ),
        migrations.AddField(
            model_name='tretment_center',
            name='Password',
            field=models.CharField(default='109141David', max_length=50),
        ),
        migrations.AddField(
            model_name='tretment_center',
            name='RepeatPassword',
            field=models.CharField(default='109141David', max_length=50),
        ),
    ]
