# Generated by Django 4.1.7 on 2023-04-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_tourismcompany_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismcompany',
            name='Password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tourismcompany',
            name='RepeatPassword',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tretment_center',
            name='Password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tretment_center',
            name='RepeatPassword',
            field=models.CharField(max_length=50),
        ),
    ]
