# Generated by Django 4.1.7 on 2023-04-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_tourismcompany_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismcompany',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='tretment_center',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/%y/%m/%d'),
        ),
    ]
