# Generated by Django 4.1.7 on 2023-04-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_tourismcompany_pictures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismcompany',
            name='role',
            field=models.CharField(default='Tourism Company', max_length=50),
        ),
        migrations.AddField(
            model_name='tretment_center',
            name='role',
            field=models.CharField(default='Treatment Center', max_length=50),
        ),
        migrations.AlterField(
            model_name='websiteusers',
            name='role',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Tourist', 'Tourist')], default='Patient', max_length=50),
        ),
    ]
