# Generated by Django 4.1.7 on 2023-04-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_tourismcompany_role_tretment_center_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteusers',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websiteusers',
            name='role',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Treatment Center', 'Treatment Center'), ('Tourist', 'Tourist'), ('Tourism Company', 'Tourism Company')], default='Patient', max_length=50),
        ),
    ]
