# Generated by Django 4.1.7 on 2023-04-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_websiteusers_age_alter_websiteusers_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismcompany',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tretment_center',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
