# Generated by Django 4.1.7 on 2023-04-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_tourismcompany_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourismcompany',
            name='identiy_verfication',
            field=models.ImageField(blank=True, null=True, upload_to='images/verify/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='tourismcompany',
            name='verfied_byadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tretment_center',
            name='identiy_verfication',
            field=models.ImageField(blank=True, null=True, upload_to='images/verify/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='tretment_center',
            name='verfied_byadmin',
            field=models.BooleanField(default=False),
        ),
    ]
