# Generated by Django 4.1.7 on 2023-04-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_tourismcompany_identiy_verfication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismcompany',
            name='identiy_verfication',
            field=models.ImageField(upload_to='images/verify/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='tretment_center',
            name='identiy_verfication',
            field=models.ImageField(upload_to='images/verify/%y/%m/%d'),
        ),
    ]
