# Generated by Django 4.1.7 on 2023-04-08 16:05

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_tourismcompany_identiy_verfication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteusers',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tourismcompany',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.0'), max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='tretment_center',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tretment_center',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.0'), max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='tretment_center',
            name='specialization',
            field=models.CharField(choices=[('Dental', 'Dental'), ('Hair Implant', 'Hair Implant'), ('Medical Tourism', 'Medical Tourism')], default='Dental', max_length=20),
        ),
        migrations.CreateModel(
            name='Treatment_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed', models.CharField(max_length=255, null=True)),
                ('treatment_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tretment_center')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.websiteusers')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment_Center_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default='0', max_digits=3, null=True)),
                ('treatment_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.tretment_center')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.websiteusers')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment_Center_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('treatment_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.tretment_center')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.websiteusers')),
            ],
        ),
        migrations.CreateModel(
            name='Tourism_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed', models.CharField(max_length=255, null=True)),
                ('tourism_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tourismcompany')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.websiteusers')),
            ],
        ),
        migrations.CreateModel(
            name='Tourism_Company_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default='0', max_digits=3, null=True)),
                ('treatment_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.tourismcompany')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.websiteusers')),
            ],
        ),
        migrations.CreateModel(
            name='Tourism_Company_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('tourism_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='api.tourismcompany')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.websiteusers')),
            ],
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.websiteusers')),
            ],
        ),
    ]
