# Generated by Django 4.1.7 on 2023-04-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_websiteusers_is_active_alter_tourismcompany_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourism_payment',
            old_name='tourism_company_id',
            new_name='tourism_company',
        ),
    ]
