# Generated by Django 4.2 on 2023-04-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_tourism_company_id_tourism_payment_tourism_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourism_company_feedback',
            name='isreplied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatment_center_feedback',
            name='isreplied',
            field=models.BooleanField(default=False),
        ),
    ]
